apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.mlflow.tokenSecret.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: dagshub
    component: mlflow-integration
  annotations:
    kubernetes.io/service-account.name: {{ .Values.mlflow.serviceAccount.name }}
type: kubernetes.io/service-account-token
